version: '2'

services:
  soavirt:
    image: neotysdevopsdemo/soavirt:latest
    hostname: soavirt
    restart: always
    cap_drop:
    - all
    cap_add:
    - NET_BIND_SERVICE
    read_only: false
    tmpfs:
    - /tmp:rw,noexec,nosuid
    environment:
    - CTP_PORT=8080
    - VIRTUALIZE_SERVER_NAME=soavirt
    - LICENSE_SERVER_HOST=IP_TO_REPLACE
    - CTP_HOST=ctp
    - XMX=2048m
    - XMS=2048m
    ports:
    - "9080:9080"
    - "9443:9443"
networks:
  default:
    external:
      name: parasoft