version: '2'

services:
  ctp:
    image: neotysdevopsdemo/ctp:latest
    hostname: ctp
    restart: always
    cap_drop:
    - all
    cap_add:
    - NET_BIND_SERVICE
    read_only: false
    tmpfs:
    - /tmp:rw,noexec,nosuid
    environment:
    - CTP_PORT=8080
    - VIRTUALIZE_SERVER_NAME=soavirt
    - LICENSE_SERVER_HOST=IP_TO_REPLACE
    - XMX=2048m
    - XMS=2048m
    ports:
    - "8180:8080"
    - "2424:2424"
networks:
  default:
    external:
      name: parasoft